version: '3'

services:
    fuzzbuilderex:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: fuzzbuilder:latest

    c-ares_pre:
        build:
            context: .
            dockerfile: ./projects/c-ares/pre.Dockerfile
        image: c-ares_pre:latest
    c-ares:
        build:
            context: .
            dockerfile: ./projects/c-ares/Dockerfile
        image: c-ares:latest

    boringssl_pre:
        build:
            context: ./projects/boringssl
            dockerfile: pre.Dockerfile
        image: fuzzbuilderex:boringssl_pre
    boringssl:
        build:
            context: ./projects/boringssl
        image: fuzzbuilderex:boringssl

    json-c_pre:
        build:
            context: .
            dockerfile: ./projects/json-c/pre.Dockerfile
        image: json-c_pre:latest
    json_c:
        build:
            context: .
            dockerfile: ./projects/json-c/Dockerfile
        image: json-c:latest

    libhtp_pre:
        build:
            context: .
            dockerfile: ./projects/libhtp/pre.Dockerfile
        image: libhtp_pre:latest
    libhtp:
        build:
            context: .
            dockerfile: ./projects/libhtp/Dockerfile
        image: libhtp:latest

    expat_pre:
        build: 
            context: ./projects/expat
            dockerfile: pre.Dockerfile
        image: fuzzbuilderex:expat_pre
    expat:
        build:
            context: ./projects/expat
        image: fuzzbuilderex:expat