version: '3'

services:
    fuzzbuilderex:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: fuzzbuilderex:base

    c-ares_pre:
        build:
            context: .
            dockerfile: ./projects/c-ares/pre.Dockerfile
        image: fuzzbuilderex:c-ares_pre
    c-ares:
        build:
            context: .
            dockerfile: ./projects/c-ares/Dockerfile
        image: fuzzbuilderex:c-ares

    boringssl_pre:
        build:
            context: ./projects/boringssl
            dockerfile: pre.Dockerfile
        image: fuzzbuilderex:boringssl_pre
    boringssl:
        build:
            context: ./projects/boringssl
        image: fuzzbuilderex:boringssl

    json-c_pre:
        build:
            context: .
            dockerfile: ./projects/json-c/pre.Dockerfile
        image: fuzzbuilderex:json-c_pre
    json_c:
        build:
            context: .
            dockerfile: ./projects/json-c/Dockerfile
        image: fuzzbuilderex:json-c

    libhtp_pre:
        build:
            context: .
            dockerfile: ./projects/libhtp/pre.Dockerfile
        image: fuzzbuilderex:libhtp_pre
    libhtp:
        build:
            context: .
            dockerfile: ./projects/libhtp/Dockerfile
        image: fuzzbuilderex:libhtp

    expat_pre:
        build: 
            context: ./projects/expat
            dockerfile: pre.Dockerfile
        image: fuzzbuilderex:expat_pre
    expat:
        build:
            context: ./projects/expat
        image: fuzzbuilderex:expat

    http-parser:
        build:
            context: ./projects/http-parser
        image: fuzzbuilderex:http-parser

    yara:
        build:
            context: ./projects/yara
        image: fuzzbuilderex:yara

    mpc:
        build:
            context: ./projects/mpc
        image: fuzzbuilderex:mpc
